1
inner caught ValueError
inner returned 2 to outer
2
